services:
  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"

  orderdb:
   container_name: orderdb
   environment:
     SA_PASSWORD: "Passw0rd23"
     ACCEPT_EULA: "Y"
   ports:
    - 1433:1433 